### ISSUE TITLE
Additional method for "xprc.xpce.OrderControlService" to retrieve the root order type

### ISSUE THREAD

**Issue by LLdaniel** [GIP-SmartMercial/xyna-factory#10]
#### Idea
There are modelling situations where a sub-workflow can be called by different root-workflows and the result is path-dependent. Meaning that in this situation it would be interesting to know if one or the other root-workflow has called the sub-workflow. 

Creating a method in `xyna-factory/modules/xprc/processing/mdmimpl/OrderControlServiceImpl/src/xprc/xpce/impl/OrderControlServiceServiceOperationImpl.java` which can manage this. 

#### Method skeleton
A method similar to this idea could do the job:
```
public OrderType getRootOrderType(XynaOrderServerExtension correlatedXynaOrder) {
        return new OrderType(correlatedXynaOrder.getRootOrder().getDestinationKey().getOrderType());
}
```

**Comment by LukasFey-GIP** [comment]
Sounds good. This change will be part of the Processing module.
