### ISSUE TITLE
Remove fileupload dependency from H5XdevFilter

### ISSUE THREAD

**Issue by csc-gip** [GIP-SmartMercial/xyna-factory#161]
https://github.com/GIP-SmartMercial/xyna-factory/blob/1f8c993601a3c447512b7ea7cbb10f331d8cc202/modules/xmcp/guihttp/filterimpl/H5XdevFilter/pom.xml#L33

It looks like the library is only used for GuiHttp filter, so it can be removed here.

**Comment by LukasFey-GIP** [comment]
removed commons-io from H5XdevFilter as well.
