### ISSUE TITLE
Releasebuild for Xynautils Logging, Exceptions and Database

### ISSUE THREAD

**Issue by LukasFey-GIP** [GIP-SmartMercial/xyna-factory#176]
It should be possible to create a realease of these components.

**Comment by csc-gip** [comment]
The should be moved to their own repos.

**Comment by LukasFey-GIP** [comment]
Opened  #177 for splitting repos.

Regardless of where the xynautils are, it should be possible to create a release.

**Comment by LukasFey-GIP** [comment]
Instead of a (dedicated) releasebuild based on the existing scripts in xynautils/install/delivery, xynautils will be build using a new script.
