### ISSUE TITLE
Workflow to build Query input out of TableInfo

### ISSUE THREAD

**Issue by johannesheucher-gip** [GIP-SmartMercial/xyna-factory#35]
Xyna shall provide a Workflow, which generates all inputs for `xnwh.persistence.Query` based on `xmcp.tables.datatypes.TableInfo`.

### FQN
`xmcp.tables.BuildQueryInput` (_ZetaFramework_)

**Comment by csc-gip** [comment]
Hallo Johannes,

ich glaube, du meinst so einen Service, wie ich ihn schon geschrieben habe.
https://10.0.10.210:8443/modeller_de-DE/xfm/Process-Modeller?tab1=%7B%22rtc%22%3A%22HTML_GUI%22%2C%22fqn%22%3A%22xmcp.NetFactoryRD.gui.html.common.datatype.TableSettings%22%2C%22type%22%3A%22dataType%22%7D

final String rootType = storable.getClass().getAnnotation(com.gip.xyna.xprc.xfractwfe.generation.XynaObjectAnnotation.class).fqXmlName();

long revision = com.gip.xyna.xfmg.xfctrl.revisionmgmt.RevisionManagement.getRevisionByClass(storable.getClass());

final var structureCache = com.gip.xyna.xnwh.persistence.xmom.XMOMStorableStructureCache.getInstance(revision);

var storableInfo = structureCache.getStructuralInformation(rootType);

// if storable not in revision check dependencies
if (storableInfo == null) {
  Set<Long> dependencies = new HashSet<Long>();
  com.gip.xyna.XynaFactory.getInstance().getFactoryManagement().getXynaFactoryControl().
                            getRuntimeContextDependencyManagement().getDependenciesRecursivly(revision, dependencies);
  for (final Long depRev : dependencies) {
    storableInfo = com.gip.xyna.xnwh.persistence.xmom.XMOMStorableStructureCache.getInstance(depRev).
                 getStructuralInformation(rootType);
    if (storableInfo != null) {
      break;
    }
  }
}
if (storableInfo == null) {
  throw new RuntimeException("Could not get xyna runtime information for datatype '" + rootType + "'");
}

final var pkColInfo = storableInfo.getColInfoByPersistenceTypeAcrossHierachy(com.gip.xyna.xprc.xfractwfe.generation.PersistenceTypeInformation.UNIQUE_IDENTIFIER);
final String primaryKeyPath = getPathForXynaObjectAccess(pkColInfo);
final boolean pkIsString = com.gip.xyna.xprc.xfractwfe.generation.AVariable.PrimitiveType.STRING.equals(pkColInfo.getPrimitiveType());

final boolean usesHistorization = storableInfo.usesHistorization();
final String timestampPath;
final String currVerPath;
if (usesHistorization) {
    final var historyTimestampInfo = storableInfo.getColInfoByPersistenceTypeAcrossHierachy(com.gip.xyna.xprc.xfractwfe.generation.PersistenceTypeInformation.HISTORIZATION_TIMESTAMP);
    final var currColInfo = storableInfo.getColInfoByPersistenceTypeAcrossHierachy(com.gip.xyna.xprc.xfractwfe.generation.PersistenceTypeInformation.CURRENTVERSION_FLAG);
    timestampPath = getPathForXynaObjectAccess(historyTimestampInfo);
    currVerPath = getPathForXynaObjectAccess(currColInfo);
} else {
    timestampPath = null;
    currVerPath = null;
}

boolean pkIsSorted = false;
boolean histIsSorted = false;
final var selectedPaths = new HashSet<String>(); // avoid duplicates
final var sortings      = new java.util.TreeMap<Integer, xnwh.persistence.SortCriterion>(); // get sorted list of SortCriteria
final var colFilters    = new ArrayList<String>();

// get paths and sortings from visible columns
for (final var col: this.getVisibleColumns()) {
    selectedPaths.add("%0%." + col.getXflPath());
    if (primaryKeyPath.equals(col.getXflPath())) {
       pkIsSorted = pkIsSorted || (col.getSortRank() != 0 && !col.getDisableSorting());
    }
    if (timestampPath != null && timestampPath.equals(col.getXflPath())) {
       histIsSorted = histIsSorted || (col.getSortRank() != 0 && !col.getDisableSorting());
    }
    if (col.getSortRank() != 0 && !col.getDisableSorting()) {
       sortings.put(java.lang.Math.abs(col.getSortRank()), new xnwh.persistence.SortCriterion("%0%." + col.getXflPath(), col.getSortRank() < 0 ));
    }
    if (!col.getDisableFiltering() && col.getFilterString() != null && !col.getFilterString().isEmpty()) {
       final var transformation = filterTransformer.getTransformation(col.getFilterTransformation());
       if (transformation != null) colFilters.add(transformation.apply(col.getFilterString(), col.getXflPath(), "String")); // ToDO: Get SimpleType of column
    }
}
// add paths for invisible columns
if (invisibleColumns != null) {
  for (final var col: invisibleColumns.getInvisibleColumnDataDefinition()) {
    selectedPaths.add("%0%." + col.getXflPath());
  }
}
// add defaults
// always select PK
selectedPaths.add("%0%." + primaryKeyPath);
if (timestampPath != null) { // always select timestamp if available
   selectedPaths.add("%0%." + timestampPath);
}
if (currVerPath != null) { // always select current version flag if available
   selectedPaths.add("%0%." + currVerPath);
}
if (!pkIsSorted) {  // always sort by PK to get consistent results
   sortings.put(Integer.MAX_VALUE-1, new xnwh.persistence.SortCriterion("%0%." + primaryKeyPath, true));
}
if (timestampPath != null && !histIsSorted) {  // always sort by history timestamp to get consistent results
   sortings.put(Integer.MAX_VALUE, new xnwh.persistence.SortCriterion("%0%." + timestampPath, true));
}
final var selMask = new SelectionMask(rootType, new ArrayList<>(selectedPaths));
final var queryParam = new QueryParameter(this.getLimit(), this.getUseHistory() && usesHistorization, new ArrayList<xnwh.persistence.SortCriterion>(sortings.values()));

// Create filter condition
if (defaultFilterCondition != null && defaultFilterCondition.getFilterCondition() != null && !defaultFilterCondition.getFilterCondition().isEmpty()) {
   colFilters.add(defaultFilterCondition.getFilterCondition());
}
var filterString = new StringBuffer(128);
for (var filter: colFilters) {
    filterString.append(filter + " && ");
}
FilterCondition filterCondition = null;
if (filterString.length() > 4) {
   filterCondition = new FilterCondition(filterString.substring(0, filterString.length() - 4));
}

return new Container(selMask, filterCondition, queryParam);
// return getImplementationOfInstanceMethods().buildQueryParameters(storable, tableSettings, invisibleColumns, defaultFilterCondition, filterTransformer);

}

private static String getPathForXynaObjectAccess(final com.gip.xyna.xnwh.persistence.xmom.XMOMStorableStructureCache.StorableColumnInformation colInfo) {

return colInfo.isFlattened() ? colInfo.getPath() : colInfo.getVariableName();

Gruß
Christoph
__________________
GIP Exyr GmbH
Hechtsheimer Str. 35-37 | 55131 Mainz | Germany

Phone: +49 6131 80124 34 | eMail: ***@***.******@***.***>
Web: www.xyna.com<http://www.xyna.com/>

GIP Exyr GmbH | Geschäftsführer: Dr. Bernd Reifenhäuser, Dr. Alexander Ebbes
Handelsregister: HRB  6870 - Amtsgericht Mainz

Von: johannesheucher-gip ***@***.***>
Gesendet: Dienstag, 18. Oktober 2022 16:02
An: GIP-SmartMercial/xyna-factory ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [GIP-SmartMercial/xyna-factory] Workflow to build Query input out of TableInfo (Issue #35)


Xyna shall provide a Workflow, which generates all inputs for xnwh.persistence.Query based on xmcp.tables.datatypes.TableInfo.

FQN

xmcp.tables.BuildQueryInput (GuiHttp)

-
